### PR TITLE
PMM-7352 Update AWS-Staging Job to use Library for spot Instance

### PR DESCRIPTION
**Pull request by puneet0191**
Tested the changes here: https://pmm.cd.percona.com/view/all/job/aws-staging-test-job/503/console

### CODE REVIEW

**Comment by puneet0191** [comment]
We Will only merge this when we merge the PHP script also to pmm-qa, it has to go together to avoid failures.

**Comment by atymchuk** [comment]
> We Will only merge this when we merge the PHP script also to pmm-qa, it has to go together to avoid failures.

I suggest that one be merged first.

**Comment by puneet0191** [comment]
> > We Will only merge this when we merge the PHP script also to pmm-qa, it has to go together to avoid failures.
> 
> I suggest that one be merged first.

yes, it will break aws-staging hence we should do it within a quick time, will merge that first and this

**Comment by puneet0191** [comment]
@atymchuk this is the other PR to add that file https://github.com/percona/pmm-qa/pull/377

**Review by atymchuk — APPROVED** [review]

**Pull request merged**
