### PR TITLE
PMM-7136 : fix pmm2-server-autobuild sync2prod

### PR DESCRIPTION
**Pull request by AlyHKafoury**

### CODE REVIEW

**Review by EvgeniyPatlan — CHANGES_REQUESTED** [review]
please provide successful build with these changes. I suggest creating a test job which will use this branch and we could check

**Comment by AlyHKafoury** [comment]
> please provide successful build with these changes. I suggest creating a test job which will use this branch and we could check

@EvgeniyPatlan 

https://pmm.cd.percona.com/job/pmm2-server-autobuild/2284/console

**Comment by EvgeniyPatlan** [comment]
@AlyHKafoury as I mentioned in slack there is still an issue with escaping:
```
ls: cannot access 'redhat': No such file or directory
ls: cannot access 'redhat/': No such file or directory
ls: cannot access 'redhat///*.rpm': No such file or directory
find: ‘../source/redhat’: No such file or directory
find: ‘../source/redhat’: No such file or directory
ls: cannot access 'debian': No such file or directory
find: paths must precede expression: libeatmydata_0.2-105.artful_amd64.deb
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec|time] [path...] [expression]
find: ‘../source’: No such file or directory
```
So this issue should be fixed

**Comment by AlyHKafoury** [comment]
@EvgeniyPatlan 

all fixed

https://pmm.cd.percona.com/job/pmm2-server-autobuild/2301/console

**Comment by atymchuk** [comment]
@AlyHKafoury Since `sync2Prod` is being used by multiple pipelines, including non-PMM ones, it's better to fork it and rename it as `sync2ProdPMM`. If we leave `sync2Prod` as is, the other teams' pipelines don't have to be tested before we commit this PR.

**Comment by AlyHKafoury** [comment]
@atymchuk I did that

**Review by EvgeniyPatlan — APPROVED** [review]
seems to be ok

**Review by atymchuk — APPROVED** [review]

**Pull request merged**
